// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeL1TABvSTzgO0QCeFxTGlTYGFRbQgtVA',
    appId: '1:698155674027:web:73779ec08af5ed70f04aee',
    messagingSenderId: '698155674027',
    projectId: 'fintrack-ocr',
    authDomain: 'fintrack-ocr.firebaseapp.com',
    storageBucket: 'fintrack-ocr.appspot.com',
    measurementId: 'G-44F246F0EY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyirIAMMFMvq-9wccPairF6ZBvmZTLECg',
    appId: '1:698155674027:android:113e0a6bed04a7f5f04aee',
    messagingSenderId: '698155674027',
    projectId: 'fintrack-ocr',
    storageBucket: 'fintrack-ocr.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBm22JqCu01yEZN26y7a1o-OKYQi8t1qIg',
    appId: '1:698155674027:ios:286ba305373c9997f04aee',
    messagingSenderId: '698155674027',
    projectId: 'fintrack-ocr',
    storageBucket: 'fintrack-ocr.appspot.com',
    iosBundleId: 'com.example.finTrackOcr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBm22JqCu01yEZN26y7a1o-OKYQi8t1qIg',
    appId: '1:698155674027:ios:5b4d317109c934ccf04aee',
    messagingSenderId: '698155674027',
    projectId: 'fintrack-ocr',
    storageBucket: 'fintrack-ocr.appspot.com',
    iosBundleId: 'com.example.finTrackOcr.RunnerTests',
  );
}
